#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "$0")/../.." && pwd)"
out="$root/contracts/out"
contracts=(FlightMarket MarketFactory MarketLens PassRegistry FlightRegistry FlightOracleConsumer MockFeeder MockERC20 OutcomeToken)

(cd "$root/contracts" && forge build --silent)

render() {
  echo "// Generated by contracts/script/export-abis.sh. Do not edit."
  for name in "${contracts[@]}"; do
    local id="$(tr '[:upper:]' '[:lower:]' <<< "${name:0:1}")${name:1}Abi"
    printf '\nexport const %s = %s as const;\n' "$id" "$(jq '.abi' "$out/$name.sol/$name.json")"
  done
}

render > "$root/app/src/lib/abi/generated.ts"
render > "$root/feeder/src/abi.ts"
